### ISSUE TITLE
Javascript Loading

### ISSUE THREAD

**Issue by mcmullengreg** [XavierUniversity/V4#12]
Need to identify the best loading pattern for local javascript to ensure it loads in the "footer" of the website for easy access to jQuery or other libraries.

**Comment by sparks12XU** [comment]
Depending on how things are structured, there could be a default local.js file that local scripts go and is loaded as needed.  That would eliminate the need to do any pre-processing at the top of the page only to send it to the bottom of the page.

**Comment by mcmullengreg** [comment]
As of right now, we'll have `header` and `footer`. I've not "established" any other structure to the site and am open to varying ideas.

Since we won't have access to CS during this process I'm debating on using a switch to define the "content" based on a query param.

Once we start actively dev-ing in CS we can readjust the include structures.

**Comment by sparks12XU** [comment]
Idea: create a  scripts directory with a `local-scripts.js` file for every site/dept etc and by default the file loads even if an empty file.

That would eliminate the need to use `cfcontent` to move the script to the bottom of the page, doesn't need to check for a script, and portable enough to move to another service using only HTML

**Comment by mcmullengreg** [comment]
@sparks12XU idea was implemented in 6c53f954f19e4071cdd6ced639795ece05abb144. Seems to allow for a lightweight option for adding localized scripting where we want it.
