### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by mcmullengreg** [XavierUniversity/V4#13]
Need to identify the typography for Bands vs Content pages. Existing solution is to use `class="subheader"` to have better font sizing across content pages.

Another specific issue falls within the OL/UL font-weights.

JB may be able to assist in defining the typography itself across the board.

**Comment by jordanbramel** [comment]
I will sit down and really nail down the font sizes and weights for band & content pages this week.

**Comment by mcmullengreg** [comment]
@jordanbramel Let me know if you need assistance in setting something up to determine the base sizes. As of right now I've been using `rem` with `1rem = 10px`. One of the accessibility issues (I'll open a new issue) is the lack of, or disorganization of headings on the banded pages. So this would be helpful to establish with that in mind.

[PxToEm](http://pxtoem.com) could prove useful in some of the sizing, but just keep in mind we'll be using REM.

**Comment by mcmullengreg** [comment]
@XavierUniversity/dev JB passed this to me for the heading typography. Seems like a good place to start. Thoughts? 

Banded: http://www.xavier.edu/marketing-and-communications/test-2.cfm
CS Template: http://www.xavier.edu/x-alumni/text.cfm

**Comment by lieslandr** [comment]
Seems OK to me. It looks like the headings get bolder as you move from h4-h6. Is that intentional?

**Comment by lieslandr** [comment]
Why are there two sets?

**Comment by mcmullengreg** [comment]
Original (Ologie) on top. Proposed on bottom (with the REM sizing on it).

**Comment by lieslandr** [comment]
Cool. Was I supposed to see that somewhere? I just want to make sure I am paying attention to the things I need to be paying attention to.

**Comment by mcmullengreg** [comment]
Don't think so. Probably should have mentioned that beforehand.

**Comment by mcmullengreg** [comment]
@jordanbramel Does this mean we're killing the `subheader` designation (at least for sizing). We can use that similar to the Muskie template and alter the color or something.

**Comment by lieslandr** [comment]
I wondered about that, too. I just came across a page that used it. I don't think it makes sense.

**Comment by mcmullengreg** [comment]
I've been using the subheader everywhere because the original font-sizing was so awful. If this remedies that, we should use it to actually call out a subheading. IMO

**Comment by lieslandr** [comment]
What is a subheading? Isn't that what the hierarchy is for in the first place?

**Comment by mcmullengreg** [comment]
For Ologie headers it reduced the font size. Which is the sole reason I used it on CS pages. CS (in the muskie template) only altered the color. From blue to grey (or something).

I'd say we could do something like that, instead of altering the font-size.

**Comment by mcmullengreg** [comment]
Remove the margin-top; keep margin bottom for CS headings only. Everything is good to go.
