### ISSUE TITLE
Button / Band naming conventions

### ISSUE THREAD

**Issue by mcmullengreg** [XavierUniversity/V4#27]
With the limited amount of colors (presumably). Should we consider modifying the names of our bands. Typical conventions are "primary, secondary, etc" instead of naming the color itself (navy, blue, etc).

Main rationale: If the "primary" color changes, the naming convention does not need to; just a color variable does. 

This is not a blocking task.

**Comment by jordanbramel** [comment]
I'm fine with either, the rationale to changing them makes sense.  As long as we have a kitchen sink somewhere as a guide - I'm okay with it.

**Comment by lieslandr** [comment]
What comes after 'secondary'? Do we have colors yet? It is safe to assume we will always have a blue-dark, blue-light, gray-dark, grey-light, and white?

**Comment by lieslandr** [comment]
Also, I forget how I am supposed to spell grey.

**Comment by mcmullengreg** [comment]
Sass has built in functions we could use for `lighten` or `darken` of any of the colors. Particularly the grey/white/black (not necessarily the blues). We can also `rgba` any of the sass vars for opacity (as needed).

@lieslandr Tertiary comes after secondary.

This would really apply to `class` names; not necessarily variable names, although it could.
- The navy would be primary
- One of the Lighter blues as secondary
- Grey/Gray as tertiary
- white as white
- black as black

**Comment by lieslandr** [comment]
I dig it. I think it makes sense to move in that direction.

**Comment by mcmullengreg** [comment]
Great. I'll continue down this path. And yes @jordanbramel we'll make sure we have some sort of documentation regarding these changes. 

As of right now it'll be for bands and buttons. Could be extended into other elements. 

Closing issue as we've resolved this for now.
